"""user

Revision ID: 1d4189161615
Revises:
Create Date: 2026-02-11 14:16:18.336634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d4189161615"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("email", sa.VARCHAR(length=100), nullable=False),
        sa.Column("password", sa.VARCHAR(length=128), nullable=True),
        sa.Column("first_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("last_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column(
            "sex",
            sa.Enum("MALE", "FEMALE", "NOT_SPECIFIED", name="gender_enum"),
            server_default="NOT_SPECIFIED",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            server_onupdate=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email = LOWER(email)", name=op.f("ck__users__email_lowercase_check")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__users")),
    )
    op.create_index(op.f("ix__users__email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__users__email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
