"""os_browser

Revision ID: 2b951efd9c2e
Revises: 941c3939068b
Create Date: 2026-02-17 09:03:50.362899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2b951efd9c2e"
down_revision: Union[str, Sequence[str], None] = "941c3939068b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "browsers",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.CheckConstraint(
            "name = LOWER(name)",
            name=op.f("ck__browsers__browser_name_lowercase_check"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__browsers")),
    )
    op.create_table(
        "operating_systems",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.CheckConstraint(
            "name = LOWER(name)",
            name=op.f("ck__operating_systems__os_name_lowercase_check"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__operating_systems")),
    )
    op.add_column(
        "user_sessions", sa.Column("os_id", sa.SmallInteger(), nullable=False)
    )
    op.add_column(
        "user_sessions", sa.Column("browser_id", sa.SmallInteger(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk__user_sessions__os_id__operating_systems"),
        "user_sessions",
        "operating_systems",
        ["os_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk__user_sessions__browser_id__browsers"),
        "user_sessions",
        "browsers",
        ["browser_id"],
        ["id"],
    )
    op.drop_column("user_sessions", "os")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_sessions",
        sa.Column(
            "os",
            postgresql.ENUM(
                "WINDOWS", "LINUX", "MACOS", "IOS", "ANDROID", name="os_enum"
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(
        op.f("fk__user_sessions__browser_id__browsers"),
        "user_sessions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk__user_sessions__os_id__operating_systems"),
        "user_sessions",
        type_="foreignkey",
    )
    op.drop_column("user_sessions", "browser_id")
    op.drop_column("user_sessions", "os_id")
    op.drop_table("operating_systems")
    op.drop_table("browsers")
    # ### end Alembic commands ###
