"""index_user_sessions

Revision ID: 755d4f51741c
Revises: 897393de358e
Create Date: 2026-03-27 18:39:42.489576

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "755d4f51741c"
down_revision: Union[str, Sequence[str], None] = "897393de358e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix__user_sessions__last_activity",
        "user_sessions",
        ["last_activity"],
        unique=False,
    )
    op.create_index(
        "ix__user_sessions__user_id_is_active",
        "user_sessions",
        ["user_id", "is_active"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix__user_sessions__user_id_is_active", table_name="user_sessions")
    op.drop_index("ix__user_sessions__last_activity", table_name="user_sessions")
    # ### end Alembic commands ###
