"""permission

Revision ID: 897393de358e
Revises: 9ef88b9f4958
Create Date: 2026-02-20 10:48:00.673239

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "897393de358e"
down_revision: Union[str, Sequence[str], None] = "9ef88b9f4958"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission_groups",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("system_key", sa.VARCHAR(length=50), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__permission_groups")),
        sa.UniqueConstraint(
            "system_key", name=op.f("uq__permission_groups__system_key")
        ),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("category", sa.VARCHAR(length=100), nullable=False),
        sa.Column("key", sa.VARCHAR(length=100), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__permissions")),
        sa.UniqueConstraint(
            "category", "key", name=op.f("uq__permissions__category_key")
        ),
    )
    op.create_table(
        "permission_group_permissions",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["permission_groups.id"],
            name=op.f("fk__permission_group_permissions__group_id__permission_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk__permission_group_permissions__permission_id__permissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "group_id", "permission_id", name=op.f("pk__permission_group_permissions")
        ),
    )
    op.create_table(
        "user_permission_groups",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["permission_groups.id"],
            name=op.f("fk__user_permission_groups__group_id__permission_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk__user_permission_groups__user_id__users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "group_id", name=op.f("pk__user_permission_groups")
        ),
    )
    op.create_table(
        "user_permissions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk__user_permissions__permission_id__permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk__user_permissions__user_id__users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "permission_id", name=op.f("pk__user_permissions")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_permissions")
    op.drop_table("user_permission_groups")
    op.drop_table("permission_group_permissions")
    op.drop_table("permissions")
    op.drop_table("permission_groups")
    # ### end Alembic commands ###
