"""os_browser_unique

Revision ID: 9ef88b9f4958
Revises: 2b951efd9c2e
Create Date: 2026-02-17 09:18:58.275894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ef88b9f4958"
down_revision: Union[str, Sequence[str], None] = "2b951efd9c2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq__browsers__name"), "browsers", ["name"])
    op.create_unique_constraint(
        op.f("uq__operating_systems__name"), "operating_systems", ["name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq__operating_systems__name"), "operating_systems", type_="unique"
    )
    op.drop_constraint(op.f("uq__browsers__name"), "browsers", type_="unique")
    # ### end Alembic commands ###
